# k8s-manifest/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: number-guessing-game
  namespace: webapps
  labels:
    app: number-guessing-game
spec:
  replicas: 3
  selector:
    matchLabels:
      app: number-guessing-game
  template:
    metadata:
      labels:
        app: number-guessing-game
    spec:
      containers:
      - name: number-guessing-game
        image: willywan/number-guessing-game:latest
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 40
          periodSeconds: 20
